name: Test
on: [push, pull_request]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-Setup-${{env.cache-name}}-
            ${{runner.os}}-Setup-
            ${{runner.os}}-
  Lint:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run lint
  Build:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
      - run: git diff --exit-code
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
  Test:
    needs: [Build, Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with: {name: output}
      - run: npm test
