name: Test
on: [push, pull_request]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: node -v
        - run: pwd
        - run: ls -l
        - run: npm install
